version: '3'

services:

  app:
    image: 'tmvdl/projects:rhon'
    build:
      context: './src/app'
    volumes:
      - './src/app:/app'
    ports:
      - '8000:80'

  docker-push:
    build: './src/app'
